### ISSUE TITLE
Automatically polyfill Promise

### ISSUE THREAD

**Issue by ernsheong** [rdy/jasmine-async-suite#2]
Hi there, it's me again.

```
PhantomJS 2.1.1 (Windows 7 0.0.0) FAILURE MESSAGE
        ReferenceError: Can't find variable: Promise in D:/workspace/class-direct/spec.bundle.js (line 64011)
        D:/workspace/class-direct/spec.bundle.js:64011:46 <- webpack:///~/jasmine-async-suite/index.js:24:0
```

May I suggest using the "transform-runtime" plugin for babel? Else I think you just need to do `require('babel-polyfill')` at the top as per usage in https://babeljs.io/docs/usage/polyfill/

Alternatively this could be polyfilled in our Karma/spec config...

**Comment by ernsheong** [comment]
Actually the real issue is that because the polyfills are coming from all over the place, the `promise instanceof Promise` is not working as expected. I think the assumption should be made that if an object has a `.then` defined, it is a Promise

**Comment by rdy** [comment]
Actually it seems reasonable to assume some kind of thenable rather than assuming a Promise implementation. Most ES6 environments should have this, I'll merge this.

**Comment by ernsheong** [comment]
Thanks. Cheers
